// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlMUgFqdhn5SOga0TxlENJhblzC1u4bQs',
    appId: '1:568224520975:web:775325eddf48d40556fc7a',
    messagingSenderId: '568224520975',
    projectId: 'easyrental-c1e2f',
    authDomain: 'easyrental-c1e2f.firebaseapp.com',
    storageBucket: 'easyrental-c1e2f.appspot.com',
    measurementId: 'G-XQWQ7BPGYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhjQzHjZBmuvRaSF-jg0WGag9fSriTe34',
    appId: '1:568224520975:android:69d7f8d6112926fe56fc7a',
    messagingSenderId: '568224520975',
    projectId: 'easyrental-c1e2f',
    storageBucket: 'easyrental-c1e2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHywVHJHwg8Z6U_4N54YF73wl-7KGnjrI',
    appId: '1:568224520975:ios:e67c288c83750a8656fc7a',
    messagingSenderId: '568224520975',
    projectId: 'easyrental-c1e2f',
    storageBucket: 'easyrental-c1e2f.appspot.com',
    iosBundleId: 'com.example.easyRentalNepal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHywVHJHwg8Z6U_4N54YF73wl-7KGnjrI',
    appId: '1:568224520975:ios:982f5cac92fc486656fc7a',
    messagingSenderId: '568224520975',
    projectId: 'easyrental-c1e2f',
    storageBucket: 'easyrental-c1e2f.appspot.com',
    iosBundleId: 'com.example.easyRentalNepal.RunnerTests',
  );
}
